server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
    - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: django
  static_configs:
  - targets:
    - localhost
    labels:
      job: django-debug
      __path__: /home/neeraj/projects/observation-app/app/debug*.log
  pipeline_stages:
  - match:
      selector: '{job="django-debug"}'
      stages:
      - tenant:
          value: "django-1"
      - drop:
          expression: ".*site-packages*"

